[fix] benches: Fix panics, remove `unsafe`
```
     Running benches/benches.rs (/tmp/target/debug/deps/benches-d5f0ac4ac54a6ba9)

running 8 tests
thread 'bench::bench_nearest_neighbour_u16' panicked at core/src/panicking.rs:221:5:
unsafe precondition(s) violated: slice::from_raw_parts_mut requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
error: test failed, to rerun pass `--bench benches`

Caused by:
  process didn't exit successfully: `/tmp/target/debug/deps/benches-d5f0ac4ac54a6ba9` (signal: 6, SIGABRT: process abort signal)
```